let imageWebp=document.querySelector('.loading-screen-ditector');let imageWebpOk=!1;if(imageWebp){if(imageWebp.width+imageWebp.height==0){imageWebpOk=!1}else{imageWebpOk=!0}}
function ibg(){let ibg=document.querySelectorAll(".ibg");for(var i=0;i<ibg.length;i++){if(ibg[i].querySelector('._webp')&&ibg[i].querySelector('._jpg')){if(ibg[i].querySelector('._webp')&&imageWebpOk==!0){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('._webp').getAttribute('src')+')';ibg[i].classList.add('_loaded')}else if(ibg[i].querySelector('._jpg')&&imageWebpOk==!1){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('._jpg').getAttribute('src')+')';ibg[i].classList.add('_loaded')}}else{if(ibg[i].querySelector('img')){ibg[i].style.backgroundImage='url('+ibg[i].querySelector('img').getAttribute('src')+')'}}}}
ibg();const isMobile={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows())}};if(isMobile.any()){document.body.classList.add('_touch');let menuArrows=document.querySelectorAll('.menu__arrow');if(menuArrows.length>0){for(let i=0;i<menuArrows.length;i++){const menuArrow=menuArrows[i];menuArrow.addEventListener("click",function(e){menuArrow.parentElement.classList.toggle('_active')})}}}else{document.body.classList.add('_pc')}
const menuLinks=document.querySelectorAll('.menu__link[data-goto]');if(menuLinks.length>0){menuLinks.forEach(menuLink=>{menuLink.addEventListener("click",onMenuLinkClick)});function onMenuLinkClick(e){const menuLink=e.target;if(menuLink.dataset.goto&&document.querySelector(menuLink.dataset.goto)){const gotoBlock=document.querySelector(menuLink.dataset.goto);const gotoBlockValue=gotoBlock.getBoundingClientRect().top+pageYOffset-document.querySelector('header').offsetHeight;if(iconMenu.classList.contains('_active')){document.body.classList.remove('_lock');iconMenu.classList.remove('_active');menuBody.classList.remove('_active')}
window.scrollTo({top:gotoBlockValue,behavior:"smooth"});e.preventDefault()}}}
const iconMenu=document.querySelector('.menu__icon');const menuBody=document.querySelector('.menu__body');const hederFon=document.querySelector('.header-fon');if(hederFon){hederFon.addEventListener("click",function(e){document.body.classList.remove('_lock');iconMenu.classList.remove('_active');menuBody.classList.remove('_active');hederFon.classList.remove('_active')})}
if(iconMenu){iconMenu.addEventListener("click",function(e){document.body.classList.toggle('_lock');iconMenu.classList.toggle('_active');menuBody.classList.toggle('_active');hederFon.classList.toggle('_active')})}
function DynamicAdapt(type){this.type=type}
DynamicAdapt.prototype.init=function(){const _this=this;this.оbjects=[];this.daClassname="_dynamic_adapt_";this.nodes=document.querySelectorAll("[data-da]");for(let i=0;i<this.nodes.length;i++){const node=this.nodes[i];const data=node.dataset.da.trim();const dataArray=data.split(",");const оbject={};оbject.element=node;оbject.parent=node.parentNode;оbject.destination=document.querySelector(dataArray[0].trim());оbject.breakpoint=dataArray[1]?dataArray[1].trim():"767";оbject.place=dataArray[2]?dataArray[2].trim():"last";оbject.index=this.indexInParent(оbject.parent,оbject.element);this.оbjects.push(оbject)}
this.arraySort(this.оbjects);this.mediaQueries=Array.prototype.map.call(this.оbjects,function(item){return '('+this.type+"-width:"+item.breakpoint+"px),"+item.breakpoint},this);this.mediaQueries=Array.prototype.filter.call(this.mediaQueries,function(item,index,self){return Array.prototype.indexOf.call(self,item)===index});for(let i=0;i<this.mediaQueries.length;i++){const media=this.mediaQueries[i];const mediaSplit=String.prototype.split.call(media,',');const matchMedia=window.matchMedia(mediaSplit[0]);const mediaBreakpoint=mediaSplit[1];const оbjectsFilter=Array.prototype.filter.call(this.оbjects,function(item){return item.breakpoint===mediaBreakpoint});matchMedia.addListener(function(){_this.mediaHandler(matchMedia,оbjectsFilter)});this.mediaHandler(matchMedia,оbjectsFilter)}};DynamicAdapt.prototype.mediaHandler=function(matchMedia,оbjects){if(matchMedia.matches){for(let i=0;i<оbjects.length;i++){const оbject=оbjects[i];оbject.index=this.indexInParent(оbject.parent,оbject.element);this.moveTo(оbject.place,оbject.element,оbject.destination)}}else{for(let i=0;i<оbjects.length;i++){const оbject=оbjects[i];if(оbject.element.classList.contains(this.daClassname)){this.moveBack(оbject.parent,оbject.element,оbject.index)}}}};DynamicAdapt.prototype.moveTo=function(place,element,destination){element.classList.add(this.daClassname);if(place==='last'||place>=destination.children.length){destination.insertAdjacentElement('beforeend',element);return}
if(place==='first'){destination.insertAdjacentElement('afterbegin',element);return}
destination.children[place].insertAdjacentElement('beforebegin',element)}
DynamicAdapt.prototype.moveBack=function(parent,element,index){element.classList.remove(this.daClassname);if(parent.children[index]!==undefined){parent.children[index].insertAdjacentElement('beforebegin',element)}else{parent.insertAdjacentElement('beforeend',element)}}
DynamicAdapt.prototype.indexInParent=function(parent,element){const array=Array.prototype.slice.call(parent.children);return Array.prototype.indexOf.call(array,element)};DynamicAdapt.prototype.arraySort=function(arr){if(this.type==="min"){Array.prototype.sort.call(arr,function(a,b){if(a.breakpoint===b.breakpoint){if(a.place===b.place){return 0}
if(a.place==="first"||b.place==="last"){return-1}
if(a.place==="last"||b.place==="first"){return 1}
return a.place-b.place}
return a.breakpoint-b.breakpoint})}else{Array.prototype.sort.call(arr,function(a,b){if(a.breakpoint===b.breakpoint){if(a.place===b.place){return 0}
if(a.place==="first"||b.place==="last"){return 1}
if(a.place==="last"||b.place==="first"){return-1}
return b.place-a.place}
return b.breakpoint-a.breakpoint});return}};const da=new DynamicAdapt("max");da.init();const blokTabs=document.querySelector('.blok-tabs');if(blokTabs){const LineBody=document.querySelector('.blok-tabs__line');window.addEventListener('resize',function(event){let TabeLink=document.querySelector('.Tabe-link__active');let Line=document.querySelector('.blok-tabs__line-span');let TabeLinkWidtw=TabeLink.offsetWidth;let TabeLinkLeft=TabeLink.getBoundingClientRect().left;let LineBodyLeft=LineBody.getBoundingClientRect().left;TabeLinkWidtw+20;SumLeft=TabeLinkLeft-LineBodyLeft;Line.style.width=`${TabeLinkWidtw + 30}px`;Line.style.left=`${SumLeft - 15}px`});document.querySelectorAll('.Tabe-link').forEach((item)=>item.addEventListener('click',function(e){e.preventDefault();const id=e.target.getAttribute('href').replace('#','');document.querySelectorAll('.Tabe-link').forEach((child)=>child.classList.remove('Tabe-link__active'));document.querySelectorAll('.Tabe-content').forEach((child)=>child.classList.remove('Tabe-content__active'));item.classList.add('Tabe-link__active');document.getElementById(id).classList.add('Tabe-content__active');let TabeLink=document.querySelector('.Tabe-link__active');let Line=document.querySelector('.blok-tabs__line-span');let TabeLinkWidtw=TabeLink.offsetWidth;let TabeLinkLeft=TabeLink.getBoundingClientRect().left;let LineBodyLeft=LineBody.getBoundingClientRect().left;TabeLinkWidtw+20;SumLeft=TabeLinkLeft-LineBodyLeft;Line.style.width=`${TabeLinkWidtw + 30}px`;Line.style.left=`${SumLeft - 15}px`}));document.querySelector('.Tabe-link').click()}
const swiper=new Swiper('.swiper',{slidesPerView:3,spaceBetween:30,navigation:{nextEl:".slaider-button_prev",prevEl:".slaider-button_next",},breakpoints:{320:{slidesPerView:1,},520:{slidesPerView:2,},1064:{slidesPerView:3,},},});const spollersArray=document.querySelectorAll('[data-spollers]');if(spollersArray.length>0){const spollersRegular=Array.from(spollersArray).filter(function(item,index,self){return!item.dataset.spollers.split(",")[0]});if(spollersRegular.length>0){initSpollers(spollersRegular)}
const spollersMedia=Array.from(spollersArray).filter(function(item,index,self){return item.dataset.spollers.split(",")[0]});if(spollersMedia.length>0){const breakpointsArray=[];spollersMedia.forEach(item=>{const params=item.dataset.spollers;const breakpoint={};const paramsArray=params.split(",");breakpoint.value=paramsArray[0];breakpoint.type=paramsArray[1]?paramsArray[1].trim():"max";breakpoint.item=item;breakpointsArray.push(breakpoint)});let mediaQueries=breakpointsArray.map(function(item){return '('+item.type+"-width:"+item.value+"px),"+item.value+','+item.type});mediaQueries=mediaQueries.filter(function(item,index,self){return self.indexOf(item)===index});mediaQueries.forEach(breakpoint=>{const paramsArray=breakpoint.split(",");const mediaBreakpoint=paramsArray[1];const mediaType=paramsArray[2];const matchMedia=window.matchMedia(paramsArray[0]);const spollersArray=breakpointsArray.filter(function(item){if(item.value===mediaBreakpoint&&item.type===mediaType){return!0}});matchMedia.addListener(function(){initSpollers(spollersArray,matchMedia)});initSpollers(spollersArray,matchMedia)})}
function initSpollers(spollersArray,matchMedia=!1){spollersArray.forEach(spollersBlock=>{spollersBlock=matchMedia?spollersBlock.item:spollersBlock;if(matchMedia.matches||!matchMedia){spollersBlock.classList.add('_init');initSpollerBody(spollersBlock);spollersBlock.addEventListener("click",setSpollerAction)}else{spollersBlock.classList.remove('_init');initSpollerBody(spollersBlock,!1);spollersBlock.removeEventListener("click",setSpollerAction)}})}
function initSpollerBody(spollersBlock,hideSpollerBody=!0){const spollerTitles=spollersBlock.querySelectorAll('[data-spoller]');if(spollerTitles.length>0){spollerTitles.forEach(spollerTitle=>{if(hideSpollerBody){spollerTitle.removeAttribute('tabindex');if(!spollerTitle.classList.contains('_active')){spollerTitle.nextElementSibling.hidden=!0}}else{spollerTitle.setAttribute('tabindex','-1');spollerTitle.nextElementSibling.hidden=!1}})}}
function setSpollerAction(e){const el=e.target;if(el.hasAttribute('data-spoller')||el.closest('[data-spoller]')){const spollerTitle=el.hasAttribute('data-spoller')?el:el.closest('[data-spoller]');const spollersBlock=spollerTitle.closest('[data-spollers]');const oneSpoller=spollersBlock.hasAttribute('data-one-spoller')?!0:!1;if(!spollersBlock.querySelectorAll('._slide').length){if(oneSpoller&&!spollerTitle.classList.contains('_active')){hideSpollersBody(spollersBlock)}
spollerTitle.classList.toggle('_active');_slideToggle(spollerTitle.nextElementSibling,500)}
e.preventDefault()}}
function hideSpollersBody(spollersBlock){const spollerActiveTitle=spollersBlock.querySelector('[data-spoller]._active');if(spollerActiveTitle){spollerActiveTitle.classList.remove('_active');_slideUp(spollerActiveTitle.nextElementSibling,500)}}}
let _slideUp=(target,duration=500)=>{if(!target.classList.contains('_slide')){target.classList.add('_slide');target.style.transitionProperty='height,margin,padding';target.style.transitionDuration=duration+'ms';target.style.height=target.offsetHeight+'px';target.offsetHeight;target.style.overflow='hidden';target.style.height=0;target.style.paddingTop=0;target.style.paddingBottom=0;target.style.marginTop=0;target.style.marginBottom=0;window.setTimeout(()=>{target.hidden=!0;target.style.removeProperty('height');target.style.removeProperty('padding-top');target.style.removeProperty('padding-bottom');target.style.removeProperty('margin-top');target.style.removeProperty('margin-bottom');target.style.removeProperty('overflow');target.style.removeProperty('transition-duration');target.style.removeProperty('transition-property');target.classList.remove('_slide')},duration)}}
let _slideDown=(target,duration=500)=>{if(!target.classList.contains('_slide')){target.classList.add('_slide');if(target.hidden){target.hidden=!1}
let height=target.offsetHeight;target.style.overflow='hidden';target.style.height=0;target.style.paddingTop=0;target.style.paddingBottom=0;target.style.marginTop=0;target.style.marginBottom=0;target.offsetHeight;target.style.transitionProperty='height,margin,padding';target.style.transitionDuration=duration+'ms';target.style.height=height+'px';target.style.removeProperty('padding-top');target.style.removeProperty('padding-bottom');target.style.removeProperty('margin-top');target.style.removeProperty('margin-bottom');window.setTimeout(()=>{target.style.removeProperty('height');target.style.removeProperty('overflow');target.style.removeProperty('transition-duration');target.style.removeProperty('transition-property');target.classList.remove('_slide')},duration)}}
let _slideToggle=(target,duration=500)=>{if(target.hidden){return _slideDown(target,duration)}else{return _slideUp(target,duration)}}
const lazyImages=document.querySelectorAll('img[data-src],source[data-srcset]');const loadMapBlock=document.querySelector('._load-map');const windowHeight=document.documentElement.clientHeight;let lazyImagesPositions=[];if(lazyImages.length>0){lazyImages.forEach(img=>{if(img.dataset.src||img.dataset.srcset){lazyImagesPositions.push(img.getBoundingClientRect().top+pageYOffset);lazyScrollCheck();ibg()}})}
window.addEventListener("scroll",lazuScroll);function lazuScroll(){if(document.querySelectorAll('img[data-src],source[data-srcset]').length>0){lazyScrollCheck();ibg()}}
function lazyScrollCheck(){let imgIndex=lazyImagesPositions.findIndex(item=>pageYOffset>item-windowHeight);if(imgIndex>=0){if(lazyImages[imgIndex].dataset.src){lazyImages[imgIndex].src=lazyImages[imgIndex].dataset.src;lazyImages[imgIndex].removeAttribute('data-src')}else if(lazyImages[imgIndex].dataset.srcset){lazyImages[imgIndex].srcset=lazyImages[imgIndex].dataset.srcset;lazyImages[imgIndex].removeAttribute('data-srcset')}
delete lazyImagesPositions[imgIndex]}}